# Generated by Django 2.2.2 on 2019-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Men', '0002_auto_20190629_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
