# Generated by Django 2.2.2 on 2019-06-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Men', '0003_auto_20190629_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men_item',
            name='image',
            field=models.ImageField(default='Gallery/T2.jpg', upload_to='gallery'),
        ),
    ]
