# Generated by Django 2.2.2 on 2019-06-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Men', '0004_auto_20190629_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men_item',
            name='category',
            field=models.CharField(choices=[('T', 'Tshirt'), ('S', 'Shirt'), ('J', 'Jeans')], default='T', max_length=2),
            preserve_default=False,
        ),
    ]
